### PR TITLE
Provide more details for the HTTP errors

### PR DESCRIPTION
**Pull request by yaxia**
This is to address the issue https://github.com/Azure/azure-ruby-asm-core/issues/12 .

The error details in the HTTP response will be returned.

### CODE REVIEW

**Comment by yaxia** [comment]
Ping~

**Comment by vishrutshah** [comment]
@yaxia LGTM!

**Comment by yaxia** [comment]
Fixed https://github.com/Azure/azure-ruby-asm-core/issues/7 as well.

**Comment by vishrutshah** [comment]
:shipit:

**Comment by yaxia** [comment]
@vishrutshah @veronicagg Would you please merge it if there is no concern? Thanks.

**Comment by veronicagg** [comment]
@yaxia looks good to me, thanks!

**Pull request merged**
