### PR TITLE
Add support for StringIO inside body headers

### PR DESCRIPTION
**Pull request by dixpac**
There is one IO which doesn't inherit from IO, StringIO(_inherits from Data_).
StringIO is especially useful in testing scenarios

### CODE REVIEW

**Comment by dixpac** [comment]
@yaxia 👍, any plans when you are going to merge this. Waiting on this ship 😃

**Comment by yaxia** [comment]
@sarangan12 could you please comment on the release plan? Thanks.

**Comment by sarangan12** [comment]
@vishrutshah Please take a look at this PR. In the original issue, you have mentioned to handle IO, File and StringIO. But file is handled only by the else condition. Since you have more context on this issue, I would like you to review

**Comment by vishrutshah** [comment]
@dixpac We appreciate your effort in improving the SDK. Thank you so much for the contribution. Changes looks good. Would you mind adding a sample unit test case into [http_request_test.rb](https://github.com/Azure/azure-ruby-asm-core/blob/master/test/unit/core/http/http_request_test.rb#L18) to make sure going forward no one breaks the expectations, please?  

Thanks again for taking time to contribute.

**Comment by dixpac** [comment]
I didn't notice any problems handling the files since file inherits from
the IO and that was handled by the first condition. Problem for me was that
StringIO inherits from Data not IO, and that was no handled.
Supporting StringIO is really useful especially for the test scenarios :)

**Comment by dixpac** [comment]
@vishrutshah  no problem 👍

**Comment by dixpac** [comment]
@vishrutshah there you I've cover all 3 cases in testes 😃

**Comment by dixpac** [comment]
Any plans on release(I need this desperately) 😃

**Comment by sarangan12** [comment]
@dixpac Am getting the release today

**Comment by sarangan12** [comment]
@dixpac The release is completed.

**Pull request merged**
