### PR TITLE
Add LICENSE.txt

### PR DESCRIPTION
**Pull request by GiriB**
Addresses #73.  

@sarangan12 Can you take a look?

### CODE REVIEW

**Review by yaxia — APPROVED** [review]

**Comment by yaxia** [comment]
@sarangan12, could you please review and merge? Thanks.

**Comment by capfei** [comment]
I'm reviewing https://github.com/clearlydefined/curated-data/pull/7551. The file headers and gemspec state Apache 2.0. Shouldn't this be adding the Apache license or are you wanting this change to MIT?

**Comment by grvillic** [comment]
What's the status of this? As @capfei states this should be Apache 2.0 based on file headers.

**Comment by GiriB** [comment]
My intention was to add a "missing" License. But Gemspec already defines the Apache 2.0. So we don't need this PR. Closing due to  inactivity.

**Pull request closed without merging**
